# Hello World

### Setting Up Environment
1. Install Anaconda
2. Install Keras in Anaconda
3. Execute the program from now on

### Imports

In [1]:
from keras.models import Sequential 
from keras.layers import Dense, Activation 

Using TensorFlow backend.


### Configuration

In [2]:
# Table
input_field_num = 100
output_field_num = 10
total_entries = 1000

### Creating Model

In [3]:
model = Sequential([ 
    Dense(total_entries, input_shape=(input_field_num,)),
    Activation('relu'),
    Dense(output_field_num),
    Activation('softmax'),
])

Instructions for updating:
Colocations handled automatically by placer.


### Compiling Model/Configuring Model

In [4]:
model.compile(optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy'])

### Data Preparation

In [5]:
import numpy as np
data = np.random.random((total_entries, input_field_num))
labels = np.random.randint(2, size=(total_entries, output_field_num))
print(data)
print(data.shape)
print(labels)
print(labels.shape)

[[0.58524933 0.70912371 0.86134789 ... 0.62282582 0.71189937 0.65258966]
 [0.48770156 0.83396641 0.02436934 ... 0.60268127 0.20839769 0.16981335]
 [0.45678772 0.2626445  0.16758051 ... 0.87623643 0.61912386 0.8753501 ]
 ...
 [0.68855043 0.10317686 0.99417426 ... 0.61696026 0.30799618 0.80723674]
 [0.63519196 0.27822622 0.82665258 ... 0.78550923 0.67639186 0.92853096]
 [0.29464999 0.95608077 0.11674296 ... 0.84946329 0.65010128 0.22826994]]
(1000, 100)
[[1 1 0 ... 1 0 0]
 [1 1 0 ... 1 0 0]
 [1 1 0 ... 0 1 0]
 ...
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 0 1 1]
 [1 0 0 ... 1 0 1]]
(1000, 10)


### Training the model

In [6]:
model.fit(data, labels, epochs=10, batch_size=32)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
1000/1000 [==============================] - 1s 695us/step - loss: 11.7648 - acc: 0.0810
Epoch 2/10
1000/1000 [==============================] - 0s 185us/step - loss: 11.5927 - acc: 0.0850
Epoch 3/10
1000/1000 [==============================] - 0s 259us/step - loss: 11.5515 - acc: 0.1290
Epoch 4/10
1000/1000 [==============================] - 0s 323us/step - loss: 11.5208 - acc: 0.1030
Epoch 5/10
1000/1000 [==============================] - 0s 211us/step - loss: 11.4802 - acc: 0.1100
Epoch 6/10
1000/1000 [==============================] - 0s 183us/step - loss: 11.4199 - acc: 0.1540
Epoch 7/10
1000/1000 [==============================] - 0s 213us/step - loss: 11.3982 - acc: 0.1520
Epoch 8/10
1000/1000 [==============================] - 0s 202us/step - loss: 11.3539 - acc: 0.1390
Epoch 9/10
1000/1000 [==============================] - 0s 224us/step - loss: 11.3094 - acc: 0.1330
Epoch 10/10
1000/1000 [=============================

Program Completed